### PR TITLE
github action adopt uv

### PR DESCRIPTION
**Pull request by darjeeling**
* adopt uv in github action to test a little faster

### CODE REVIEW

**Comment by hexoul** [comment]
Thanks for trying to improve. But I'm not sure this approach is good.
From invoked Github action jobs, there is no big difference. Meanwhile, dependency will be added and maintenance cost will be increased. `uv` is not de facto now.

**Comment by minwoox** [comment]
@hexoul It seems like uv is becoming the de facto. 😅 
https://www.reddit.com/r/Python/comments/1ghiln0/state_of_the_art_python_in_2024/?rdt=57259

**Comment by ikhoon** [comment]
> * adopt uv in github action to test a little faster

Could you share a number on how much faster the tests run?

**Comment by darjeeling** [comment]
@ikhoon 
in most cases, 30 seconds faster for installation

**Comment by darjeeling** [comment]
@minwoox IMHO, we have other tools that support almost same format. so we can change other tool if it's not standard 
- [PEP-621](https://peps.python.org/pep-0621/)
- [PEP-735](https://peps.python.org/pep-0735/)

**Comment by minwoox** [comment]
@darjeeling What I meant was, I preferred using uv. 😉

**Comment by corona10** [comment]
Well, my two cents is that using uv has more upside rather than downside. 
(The only downside would be future license issues if Astral change their policy)
Since uv provides a `drop-in-replacement` interface with `pip`, there will be no issue compared to using pip unless we use a non-standard feature that is only provided by uv.

Many Python projects these days (including product engineering) begin to start using uv due to performance issue of pip, I think that we can just start to use it and replace it later if the uv makes any trouble.

But we should only use standard feature only.

**Comment by hexoul** [comment]
After taking a look more into pros/cons from many sources and arguments in the thread @minwoox referred, I weakly agreed. Except for license issue, uv looks cool and can rollback if problem occurs as @corona10 said. However, performance issue from pip is not sensitive in this project and there are ongoing discussions. So, adopting uv makes sense, but can we say that now is good time to apply?

**Comment by minwoox** [comment]
> performance issue from pip is not sensitive 

Right, we don't have any performance issues with pip because this project is relatively small.
It's just that uv is getting popular, and since we can always revert it so, there was no reason not to give it a try.
Since you're maintaining this repository, it's your call. I will go along with whatever decision you make. 😉

**Comment by ikhoon** [comment]
Thanks @darjeeling for your interest and contribution to centraldogma-python. This project is mostly maintained by contributing @hexoul personal effort. I don't want to use his resources aside from bug fixes and new features. 

If there is a problem with CI builds, we need to fix it. However, if we simply want to try it out, I think it's not too late to do it the next time we feel a problem in `pip`.

**Review by hexoul — APPROVED** [review]
Thanks for all comments, supports and considerations. Let us try.

**Pull request merged**
